<?php

return array (
  'management' => 'Gestión de vehículos',
  'breadcrumb' => 'Carousel',
  'dashboard' => 'Dashboard',
  'new_slide' => 'Nuevo',
  'edit' => 'Editar',
  'view' => 'Vista',
  'delete' => 'Suprimir',
  'cancel' => 'Cancelar',
  'active' => 'Activo',
  'inactive' => 'Inactivo',
  'image_header' => 'Imagen',
  'title_header' => 'Título',
  'status_header' => 'Estado',
  'dates_header' => 'Fechas',
  'actions_header' => 'Acciones',
  'no_slides' => 'No hay diapositivas carrusel encontradas',
  'delete_confirmation_title' => 'Eliminación de la confirmación',
  'delete_confirmation_message' => '¿Estás seguro de que quieres eliminar esta diapositiva de carrusel?',
  'delete_confirmation_warning' => 'Esta acción no puede ser cancelada.',
  'slides_description' => 'Administrar diapositivas carrusel página principal',
  'create_first_slide' => 'Crear su primera página de inicio carousel diapositiva',
  'create_first_slide_button' => 'Crear primera diapositiva',
  'slides' => 'Slide del Carosello',
  'from' => 'Desde',
  'to' => 'A',
);
