<?php

return array (
  'title' => '[es] Ingaggi',
  'gigs' => '[es] Ingaggi',
  'my_gigs' => '[es] I Miei Ingaggi',
  'all_gigs' => '[es] Tutti gli Ingaggi',
  'open_gigs' => '[es] Ingaggi Aperti',
  'closed_gigs' => '[es] Ingaggi Chiusi',
  'translation_jobs' => '[es] Lavori di Traduzione',
  'translation_jobs_description' => '[es] Traduci poesie e guadagna',
  'create_gig' => '[es] Crea Ingaggio',
  'edit_gig' => '[es] Modifica Ingaggio',
  'manage_gigs' => '[es] Gestisci Ingaggi',
  'apply_gig' => '[es] Candidati',
  'close_gig' => '[es] Chiudi Ingaggio',
  'reopen_gig' => '[es] Riapri Ingaggio',
  'delete_gig' => '[es] Elimina Ingaggio',
  'fields' => 
  array (
    'title' => '[es] Titolo Posizione',
    'description' => '[es] Descrizione',
    'requirements' => '[es] Requisiti',
    'compensation' => '[es] Compenso',
    'deadline' => '[es] Scadenza Candidature',
    'event' => '[es] Evento',
    'group' => '[es] Gruppo',
    'category' => '[es] Categoria',
    'type' => '[es] Tipo di Ingaggio',
    'language' => '[es] Lingua',
    'location' => '[es] Località',
    'is_remote' => '[es] Lavoro Remoto',
    'is_urgent' => '[es] Urgente',
    'is_featured' => '[es] In Evidenza',
    'max_applications' => '[es] Numero Massimo Candidature',
    'allow_group_admin_edit' => '[es] Permetti Modifica Admin Gruppo',
  ),
  'types' => 
  array (
    'artist_poet' => '[es] Artista/Poeta',
    'mc_guest' => '[es] MC/Ospite',
    'technical_support' => '[es] Supporto Tecnico',
    'volunteer' => '[es] Volontaria/Volontario',
  ),
  'categories' => 
  array (
    'traduzione' => '[es] Traduzione',
    'poetry_slam' => '[es] Poetry Slam',
    'theater' => '[es] Teatro',
    'music' => '[es] Musica',
    'dance' => '[es] Danza',
    'comedy' => '[es] Commedia',
    'workshop' => '[es] Workshop',
    'festival' => '[es] Festival',
    'conference' => '[es] Conferenza',
    'exhibition' => '[es] Mostra',
    'competition' => '[es] Competizione',
    'other' => '[es] Altro',
  ),
  'status' => 
  array (
    'title' => '[es] Stato',
    'open' => '[es] Aperto',
    'closed' => '[es] Chiuso',
    'urgent' => '[es] Urgente',
    'featured' => '[es] In Evidenza',
    'expired' => '[es] Scaduto',
    'filled' => '[es] Coperto',
    'cancelled' => '[es] Annullato',
  ),
  'filters' => 
  array (
    'title' => '[es] Filtri e Ricerca',
    'search' => '[es] Cerca ingaggi...',
    'filter_by_category' => '[es] Filtra per categoria',
    'filter_by_type' => '[es] Filtra per tipo',
    'filter_by_location' => '[es] Filtra per località',
    'filter_by_status' => '[es] Filtra per stato',
    'sort_by' => '[es] Ordina per',
    'sort_options' => 
    array (
      'recent' => '[es] Più recenti',
      'deadline' => '[es] Scadenza',
      'urgent' => '[es] Urgenti',
      'featured' => '[es] In evidenza',
      'compensation' => '[es] Compenso',
      'applications' => '[es] Numero candidature',
    ),
    'select_category' => '[es] Seleziona categoria',
    'select_type' => '[es] Seleziona tipo',
    'select_language' => '[es] Seleziona lingua',
    'select_event' => '[es] Seleziona evento',
    'select_group' => '[es] Seleziona gruppo',
    'show_remote' => '[es] Solo remoto',
    'show_urgent' => '[es] Solo urgenti',
    'show_featured' => '[es] Solo in evidenza',
  ),
  'management' => 
  array (
    'title' => '[es] Gestione Ingaggi',
    'manage_applications' => '[es] Gestisci Candidature',
    'view_applications' => '[es] Visualizza Candidature',
    'send_global_message' => '[es] Invia Messaggio Globale',
    'global_message_placeholder' => '[es] Scrivi un messaggio per tutti i professionisti...',
    'send_message' => '[es] Invia Messaggio',
    'message_sent' => '[es] Messaggio inviato con successo!',
    'extend_deadline' => '[es] Estendi Scadenza',
    'new_deadline' => '[es] Nuova Scadenza',
    'deadline_extended' => '[es] Scadenza estesa con successo!',
    'close_applications' => '[es] Chiudi Candidature',
    'reopen_applications' => '[es] Riapri Candidature',
    'close_confirm' => '[es] Sei sicuro di voler chiudere le candidature?',
    'reopen_confirm' => '[es] Sei sicuro di voler riaprire le candidature?',
    'delete_confirm' => '[es] Sei sicuro di voler eliminare questo ingaggio?',
    'allow_group_admin_edit_help' => '[es] Permetti agli admin del gruppo di modificare questo ingaggio',
  ),
  'actions' => 
  array (
    'read' => '[es] Leggi',
    'share' => '[es] Condividi',
    'close_gig' => '[es] Chiudi Ingaggio',
    'reopen_gig' => '[es] Riapri Ingaggio',
    'send_global_message' => '[es] Invia Messaggio Globale',
    'view_gig' => '[es] Vedi Ingaggio',
    'message' => 'Mensaje',
    'message_placeholder' => '[es] Scrivi il tuo messaggio per tutti gli utenti...',
    'send_message' => '[es] Invia Messaggio',
    'confirm_close' => '[es] Conferma Chiusura',
    'confirm_close_text' => '[es] Sei sicuro di voler chiudere questo ingaggio? Non sarà più possibile ricevere nuove candidature.',
    'confirm_reopen' => '[es] Conferma Riapertura',
    'confirm_reopen_text' => '[es] Sei sicuro di voler riaprire questo ingaggio? Potrà ricevere nuove candidature.',
  ),
  'remote' => '[es] Remoto',
  'applications' => 
  array (
    'title' => '[es] Candidature',
    'my_applications' => '[es] Le Mie Candidature',
    'pending_applications' => '[es] Candidature in Attesa',
    'accepted_applications' => '[es] Candidature Accettate',
    'rejected_applications' => '[es] Candidature Rifiutate',
    'manage_applications' => '[es] Gestisci Candidature',
    'applications_list' => '[es] Lista Candidature',
    'total_applications' => '[es] Candidature Totali',
    'max_positions' => '[es] Posizioni Massime',
    'pending' => '[es] In Attesa',
    'accepted' => '[es] Accettata',
    'rejected' => '[es] Rifiutata',
    'withdrawn' => '[es] Ritirata',
    'experience' => '[es] Esperienza',
    'portfolio' => '[es] Portfolio',
    'view_portfolio' => '[es] Vedi Portfolio',
    'compensation_expectation' => '[es] Aspettative Compenso',
    'accept' => '[es] Accetta',
    'reject' => '[es] Rifiuta',
    'withdraw' => '[es] Ritira Candidatura',
    'confirm_accept' => '[es] Conferma Accettazione',
    'confirm_accept_text' => '[es] Sei sicuro di voler accettare questa candidatura?',
    'confirm_reject' => '[es] Conferma Rifiuto',
    'confirm_reject_text' => '[es] Sei sicuro di voler rifiutare questa candidatura?',
    'withdraw_confirm' => '[es] Sei sicuro di voler ritirare la tua candidatura?',
    'no_applications' => '[es] Nessuna Candidatura',
    'no_applications_description' => '[es] Non ci sono ancora candidature per questo ingaggio.',
    'apply' => '[es] Candidati',
    'message' => '[es] Messaggio di Candidatura',
    'message_placeholder' => '[es] Presentati e spiega perché sei interessato a questa posizione...',
    'experience_placeholder' => '[es] Descrivi la tua esperienza rilevante...',
    'portfolio_placeholder' => '[es] Link al tuo portfolio o sito web...',
    'availability_placeholder' => '[es] Descrivi la tua disponibilità...',
    'compensation_expectation_placeholder' => '[es] Le tue aspettative di compenso...',
    'submit_application' => '[es] Invia Candidatura',
    'application_sent' => '[es] Candidatura inviata con successo!',
    'application_withdrawn' => '[es] Candidatura ritirata con successo!',
    'already_applied' => '[es] Ti sei già candidato per questo ingaggio',
  ),
  'messages' => 
  array (
    'application_accepted' => '[es] Candidatura accettata con successo!',
    'application_rejected' => '[es] Candidatura rifiutata con successo!',
    'gig_closed' => '[es] Ingaggio chiuso con successo!',
    'gig_reopened' => '[es] Ingaggio riaperto con successo!',
    'gig_shared' => '[es] Ingaggio condiviso con :count utenti!',
    'global_message_sent' => '[es] Messaggio globale inviato a :count utenti!',
    'audience_not_allowed' => '[es] Gli utenti audience non possono accedere agli ingaggi',
  ),
  'stats' => 
  array (
    'total_gigs' => '[es] Ingaggi Totali',
    'open_gigs_count' => '[es] Ingaggi Aperti',
    'urgent_gigs_count' => '[es] Ingaggi Urgenti',
    'total_applications' => '[es] Candidature Totali',
    'applications' => '[es] Candidature',
    'pending_applications_count' => '[es] Candidature in Attesa',
    'accepted_applications_count' => '[es] Candidature Accettate',
    'my_applications_count' => '[es] Le Mie Candidature',
    'my_gigs_count' => '[es] I Miei Ingaggi',
    'browse_all' => '[es] Sfoglia Tutti',
  ),
  'placeholders' => 
  array (
    'title' => '[es] Es: Performer Poetry Slam per Evento Estivo',
    'description' => '[es] Descrivi dettagliatamente la posizione, le responsabilità e le aspettative...',
    'requirements' => '[es] Specifica i requisiti, competenze e esperienze richieste...',
    'compensation' => '[es] Specifica il compenso offerto (es: €200, gratuito, percentuale...)',
    'location' => '[es] Città, regione o "Remoto"',
    'deadline' => '[es] Seleziona data e ora di scadenza',
    'max_applications' => '[es] Numero massimo di candidature accettate',
  ),
  'help' => 
  array (
    'title' => '[es] Sii specifico e accattivante nel titolo',
    'description' => '[es] Fornisci tutti i dettagli necessari per attirare i candidati giusti',
    'requirements' => '[es] Sii chiaro sui requisiti per evitare candidature inappropriate',
    'compensation' => '[es] Specifica chiaramente il compenso per attirare candidati qualificati',
    'deadline' => '[es] Imposta una scadenza ragionevole per ricevere candidature di qualità',
    'max_applications' => '[es] Imposta un limite ragionevole per gestire le candidature',
    'is_remote' => '[es] Seleziona se il lavoro può essere svolto da remoto',
    'is_urgent' => '[es] Marca come urgente per attirare più attenzione',
    'is_featured' => '[es] Metti in evidenza per dare più visibilità',
    'event' => '[es] Associa l\'ingaggio a un evento specifico',
    'group' => '[es] Associa l\'ingaggio a un gruppo specifico',
    'allow_group_admin_edit' => '[es] Se attivato, gli admin del gruppo potranno modificare questo ingaggio',
  ),
  'languages' => 
  array (
    'italian' => '[es] Italiano',
    'english' => '[es] Inglese',
    'french' => '[es] Francese',
    'german' => '[es] Tedesco',
    'spanish' => '[es] Spagnolo',
    'portuguese' => '[es] Portoghese',
    'russian' => '[es] Russo',
    'chinese' => '[es] Cinese',
    'japanese' => '[es] Giapponese',
    'arabic' => '[es] Arabo',
    'other' => '[es] Altro',
  ),
  'breadcrumb' => 
  array (
    'gigs' => '[es] Ingaggi',
    'my_gigs' => '[es] I Miei Ingaggi',
    'create_gig' => '[es] Crea Ingaggio',
    'edit_gig' => '[es] Modifica Ingaggio',
    'manage_gigs' => '[es] Gestisci Ingaggi',
    'applications' => '[es] Candidature',
  ),
  'create' => 
  array (
    'publication_options' => '[es] Opzioni di Pubblicazione',
  ),
  'about_author' => '[es] Informazioni Autore',
  'organizer_section' => 
  array (
    'title' => '[es] I Miei Eventi',
    'gigs' => '[es] Ingaggi',
    'add_gig' => '[es] Aggiungi Ingaggio',
    'no_events' => '[es] Non hai ancora eventi',
    'create_event_first' => '[es] Crea prima un evento per aggiungere ingaggi',
  ),
  'notifications' => 
  array (
    'shared_title' => '[es] Nuovo Ingaggio Condiviso',
    'shared_message' => '[es] :title per l\'evento :event - Posizione: :type - Luogo: :location - Scadenza: :deadline',
  ),
);
