<?php

return array (
  'media' => '[es] Media',
  'photo' => '[es] Foto',
  'video' => '[es] Video',
  'description' => '[es] Descrizione',
  'interactions' => '[es] Interazioni',
  'likes' => '[es] Mi piace',
  'comments' => '[es] Commenti',
  'views' => '[es] Visualizzazioni',
  'author' => '[es] Autore',
  'photos' => '[es] Foto',
  'uploaded' => '[es] Caricato',
  'dimensions' => '[es] Dimensioni',
  'file_size' => '[es] Dimensione file',
  'format' => '[es] Formato',
  'related_photos' => '[es] Foto Correlate',
  'write_comment' => '[es] Scrivi un commento...',
  'post_comment' => '[es] Pubblica Commento',
  'login_to_comment' => '[es] Accedi per commentare',
  'no_comments_yet' => '[es] Nessun commento ancora',
  'comment_posted_success' => '[es] Commento pubblicato con successo!',
  'error_posting_comment' => '[es] Errore durante la pubblicazione del commento',
  'session_expired' => '[es] Sessione scaduta, ricarica la pagina',
  'connection_error' => '[es] Errore di connessione',
  'confirm_delete_comment' => '[es] Sei sicuro di voler eliminare questo commento?',
  'comment_deleted_success' => '[es] Commento eliminato con successo',
  'error_deleting_comment' => '[es] Errore durante l\'eliminazione del commento',
  'error_loading_comments' => '[es] Errore nel caricamento dei commenti',
  'photo_info' => '[es] Informazioni Foto',
);
