<?php

return array (
  'permissions' => '[es] Permessi',
  'roles' => '[es] Ruoli',
  'users' => '[es] Utenti',
  'total_roles' => '[es] Ruoli Totali',
  'total_permissions' => '[es] Total Permissions',
  'total_users' => '[es] Total Users',
  'roles_with_permissions' => '[es] Ruoli Attivi',
  'role_management' => '[es] 👥 Gestione',
  'role_security' => '[es] 🔐 Sicurezza',
  'role_users' => '[es] 👤 Utenti',
  'role_statistics' => '[es] 📊 Statistiche',
  'manage_users' => '[es] Gestisci Utenti',
  'users_description' => '[es] Gestisci tutti gli utenti del sistema e assegna ruoli e permessi',
  'export' => '[es] Esporta',
  'bulk_assign' => '[es] Assegnazione di Massa',
  'search_users' => '[es] Cerca Utenti',
  'search_placeholder' => '[es] Cerca per nome, email o nickname...',
  'filter_by_role' => '[es] Filtra per Ruolo',
  'all_roles' => '[es] Tutti i Ruoli',
  'filter_by_status' => '[es] Filtra per Stato',
  'all_status' => '[es] Tutti gli Stati',
  'status_active' => 'Activo',
  'status_inactive' => 'Inactivo',
  'items_per_page' => '[es] Elementi per Pagina',
  'system_users' => '[es] Utenti del Sistema',
  'name' => '[es] Nome:',
  'email' => 'Correo',
  'nickname' => '[es] Nickname:',
  'status' => '[es] Stato',
  'actions' => '[es] Azioni',
  'no_nickname' => '[es] Nessun nickname',
  'no_roles' => '[es] No roles',
  'no_direct_permissions' => '[es] Nessun permesso diretto',
  'view_details' => '[es] Visualizza Dettagli',
  'edit_roles' => '[es] Modifica Ruoli',
  'edit_permissions' => '[es] Modifica Permessi',
  'delete_user' => '[es] Elimina Utente',
  'view' => 'Ver',
  'manage_roles' => '[es] Gestisci Ruoli',
  'manage_permissions' => '[es] Gestisci Permessi',
);
