<?php

return array (
  'premium' => '[es] Premium',
  'packages' => '[es] Pacchetti',
  'free_package' => '[es] Gratuito',
  'price_monthly' => '[es] al mese',
  'days' => '[es] giorni',
  'video_limit' => '[es] Limite Video',
  'features' => '[es] Caratteristiche',
  'select_plan' => '[es] Seleziona Piano',
  'purchase' => '[es] Acquista',
  'checkout' => '[es] Checkout',
  'payment_method' => '[es] Metodo di Pagamento',
  'terms_accepted' => '[es] Accetto i termini e condizioni',
  'payment_successful' => '[es] Pagamento Completato',
  'manage_subscription' => '[es] Gestisci Abbonamento',
  'current_plan' => '[es] Piano Attuale',
  'subscription_status' => '[es] Stato Abbonamento',
  'subscription_active' => 'Activo',
  'days_remaining' => '[es] Giorni Rimanenti',
  'upgrade_required' => '[es] Aggiornamento Richiesto',
  'upgrade_message' => '[es] Hai raggiunto il limite di video gratuiti. Aggiorna il tuo piano per caricare più video.',
  'compare_packages' => '[es] Confronta Pacchetti',
  'best_value' => '[es] Miglior Valore',
  'most_popular' => '[es] Più Popolare',
  'faq' => '[es] FAQ',
  'frequently_asked_questions' => '[es] Domande Frequenti',
  'how_many_videos' => '[es] Quanti video posso caricare?',
  'how_many_videos_answer' => '[es] Il numero di video dipende dal tuo piano. Il piano gratuito permette 3 video, mentre i piani premium permettono da 10 a 100 video.',
  'can_i_upgrade' => '[es] Posso aggiornare il mio piano?',
  'can_i_upgrade_answer' => '[es] Sì, puoi aggiornare il tuo piano in qualsiasi momento. Il nuovo piano sarà attivo immediatamente.',
  'payment_methods_answer' => '[es] Accettiamo tutte le principali carte di credito e debito tramite Stripe.',
);
