<?php

return array (
  'title' => 'Gedichte',
  'poems' => 'Gedichte',
  'untitled' => 'Kein Titel',
  'my_poems' =>
  array (
    'title' => 'Meine Gedichte',
    'total_poems' => 'Insgesamt Gedichte',
    'published' => 'Veröffentlicht',
    'drafts' => 'Einrichtungen',
    'total_likes' => 'Ich mag total',
    'your_poems' => 'Ihr Gedicht',
    'view_drafts' => 'Skizzen anzeigen',
    'create_new' => 'Neues erstellen',
    'published_on' => 'Veröffentlicht am',
    'created_on' => 'Erstellt die',
    'no_poems' => 'Sie haben noch keine Poesie geschaffen',
    'no_poems_description' => 'Schreiben und Teilen Sie Ihre Gedichte mit der Community',
    'create_first_poem' => 'Erstellen Sie Ihr erstes Gedicht',
  ),
  'fields' =>
  array (
    'title' => 'Titel',
    'content' => 'Inhalt',
    'description' => 'Warenbezeichnung',
    'category' => 'Kategorie',
    'poem_type' => 'Art der Poesie',
    'language' => 'Sprache',
    'tags' => 'Tag',
    'thumbnail' => 'Bild vergrößern',
    'is_public' => 'Öffentliche',
    'is_draft' => 'Sparen Sie sich als Entwurf',
    'translation_available' => 'Verfügbar für Übersetzung',
    'translation_price' => 'Übersetzungspreis',
    'translation_notes' => 'Anmerkungen zur Übersetzung',
    'translation_job_available' => 'Erhältlich als Übersetzungsarbeit',
    'translation_base_price' => 'Grundübersetzung',
    'translation_negotiable' => 'Verhandlungspreis',
    'translation_instructions' => 'Übersetzungshinweise',
    'created_at' => 'Erstellt die',
    'published_at' => 'Veröffentlicht am',
    'draft_saved_at' => 'Bozza hat die',
    'view_count' => 'Ansichten',
    'like_count' => 'Mir gefällt es',
    'comment_count' => 'Bemerkungen',
  ),
  'actions' =>
  array (
    'create' => 'Poesie erstellen',
    'like' => 'Mir gefällt es',
    'bookmark' => 'Zu den Lesezeichen hinzufügen',
    'search' => 'Suche',
    'read' => 'Weiterlesen',
    'request_translation' => 'Übersetzung anfordern',
    'available_languages' => 'Verfügbare Sprachen',
  ),
  'create' =>
  array (
    'title' => 'Neues Gedicht erstellen',
    'subtitle' => 'Schreiben und teilen Sie Ihr Gedicht',
    'title_placeholder' => 'Betreten Sie den Titel der Poesie',
    'tags_placeholder' => 'liebe, natur, leben (getrennt von kommas)',
    'tags_help' => 'Geben Sie separate Komma-Tags ein, um die Suche zu erleichtern',
    'description_placeholder' => 'Kurzbeschreibung der Poesie (optional)',
    'description_help' => 'Eine kurze Beschreibung, die den Lesern hilft, den Inhalt zu verstehen',
    'content_placeholder' => 'Schreiben Sie Ihr Gedicht hier. .',
    'content_help' => 'Benutze sie, um die Schlampen zu trennen. Sie können den Text mit HTML formatieren.',
    'thumbnail_help' => 'Laden Sie ein Coverbild für Ihr Gedicht hoch (optional)',
    'publication_options' => 'Publikationsoptionen',
    'public_help' => 'Poesie für alle Benutzer sichtbar machen',
    'draft_help' => 'Speichern Sie als Entwurf, um es später abzuschließen',
    'save_draft' => 'Sparen Sie den Entwurf',
    'publish' => 'Öffentliche',
    'official_translations' => 'Offizielle Übersetzungen',
    'official_translations_help' => 'Fügen Sie Ihre offiziellen Übersetzungen in andere Sprachen hinzu',
    'add_translation' => 'Übersetzung hinzufügen',
    'translation' => '♪',
    'translation_note' => 'Offizielle Übersetzungen werden automatisch genehmigt',
    'translation_notes_placeholder' => 'Zusätzliche Hinweise für diese Übersetzung (optional)',
    'translation_job_help' => 'Aktivieren Sie diese Option, Poesie als Übersetzungsgig zur Verfügung zu stellen',
    'translation_negotiable_help' => 'Erlauben Sie Übersetzern, einen anderen Preis vorzuschlagen',
    'translation_instructions_placeholder' => 'Spezifische Anweisungen für Übersetzer (z.B. Schritt halten, verwenden Sie einen formalen Ton, etc.)',
  ),
  'edit' =>
  array (
    'title' => 'Poesie bearbeiten',
    'subtitle' => 'Bearbeiten Sie die Details Ihres Gedichts',
    'remove_thumbnail' => 'Abdeckbild entfernen',
    'status_info' => 'Staatliche Informationen',
    'save_draft' => 'Sparen Sie den Entwurf',
    'update' => 'Poesie aktualisieren',
  ),
  'drafts' =>
  array (
    'title' => 'Meine Entwürfe',
    'total_drafts' => 'Insgesamt',
    'recent_drafts' => 'Vor kurzem',
    'near_complete' => 'Fast komplett',
    'total_words' => 'Insgesamt',
    'your_drafts' => 'Ihre Skizzen',
    'description' => 'Verwalten Sie Ihre Entwürfe und füllen Sie Ihre Arbeits Gedichte',
    'view_all_poems' => 'Alle Gedichte anzeigen',
    'create_new' => 'Neue Entwürfe erstellen',
    'near_complete_badge' => 'Fast komplett',
    'in_progress' => 'Arbeit',
    'untitled' => 'Kein Titel',
    'no_content' => 'Kein Inhalt',
    'completion' => 'Abschluss',
    'never_saved' => 'Nie gerettet',
    'publish' => 'Öffentliche',
    'duplicate' => 'Duplikat',
    'publish_confirm' => 'Bist du sicher, dass du diesen Entwurf veröffentlichen willst?',
    'duplicate_confirm' => 'Bist du sicher, dass du diesen Entwurf duplizieren willst?',
    'duplicate_error' => 'Fehler bei der Entwurfsvervielfältigung',
    'no_drafts' => 'Sie haben noch keine Entwürfe',
    'no_drafts_description' => 'Schreiben Sie ein neues Gedicht oder erstellen Sie einen Entwurf',
    'create_first_draft' => 'Erstellen Sie Ihren ersten Entwurf',
    'view_published_poems' => 'Veröffentlichte Gedichte anzeigen',
  ),
  'bookmarks' =>
  array (
    'title' => 'Meine Lesezeichen',
    'total_bookmarks' => 'Gesamte Lesezeichen',
    'recent_bookmarks' => 'Aktuelle Zeichen',
    'authors' => 'Autoren',
    'categories' => 'Kategorien',
    'your_bookmarks' => 'Ihre Lesezeichen',
    'description' => 'Zugriff auf die Gedichte, die Sie gespeichert haben',
    'clear_all' => 'Alles löschen',
    'explore_poems' => 'Gedichte entdecken',
    'bookmarked_on' => 'Speichern Sie die',
    'remove_bookmark' => 'Lesezeichen entfernen',
    'remove_confirm' => 'Sind Sie sicher, dass Sie dieses Gedicht von den Lesezeichen entfernen wollen?',
    'remove_error' => 'Fehler beim Entfernen des Lesezeichens',
    'clear_all_confirm' => 'Sind Sie sicher, dass Sie alle Lesezeichen abbrechen möchten?',
    'clear_all_error' => 'Fehler beim Löschen von Lesezeichen',
    'no_bookmarks' => 'Du hast noch keine Lesezeichen',
    'no_bookmarks_description' => 'Speichern Sie die Gedichte, die Sie gerne finden sie leicht',
    'view_liked_poems' => 'Wunschgedichte ansehen',
  ),
  'liked' =>
  array (
    'title' => 'Gedichte mögen',
    'total_liked' => 'Gedichte mögen',
    'recent_likes' => 'Ich mag es vor kurzem',
    'authors' => 'Autoren',
    'categories' => 'Kategorien',
    'your_liked_poems' => 'Die Gedichte, die Sie mochten',
    'description' => 'Sehen Sie die Gedichte, die Sie gelegt haben',
    'view_bookmarks' => 'Lesezeichen ansehen',
    'explore_poems' => 'Gedichte entdecken',
    'liked_on' => 'Angenehm',
    'unlike' => 'Ich mag es nicht mehr',
    'unlike_confirm' => 'Bist du sicher, dass du mich von diesem Gedicht entfernen willst?',
    'unlike_error' => 'Fehler bei der Entfernung von I like',
    'no_liked_poems' => 'Ich mag kein Gedicht',
    'no_liked_poems_description' => 'Entdecken Sie die Gedichte und legen Sie es Mir gefällt, was Sie mögen',
  ),
  'filters' =>
  array (
    'recent' => 'Vor kurzem',
    'popular' => 'Beliebtheit',
    'featured' => 'Highlights',
    'drafts' => 'Einrichtungen',
    'filter_by_category' => 'Filter nach Kategorie',
    'filter_by_language' => 'Filter nach Sprache',
    'bookmarks' => 'Lesezeichen',
    'liked' => 'Angemeldet',
    'category' => 'Kategorie',
    'sort' => 'Sortieren nach',
    'oldest' => 'Alter',
    'alphabetical' => 'Alphabetisch',
    'sort_options' => [
      'recent' => 'Neueste',
      'oldest' => 'Älteste',
      'popular' => 'Beliebteste',
      'alphabetical' => 'Nach Titel',
      'author' => 'Nach Autor',
      'likes' => 'Nach Likes',
      'views' => 'Nach Aufrufen',
    ],
  ),
  'status' =>
  array (
    'draft' => 'Bozza',
    'published' => 'Veröffentlicht',
    'private' => 'Privatpersonen',
    'featured' => 'Highlights',
    'bookmarked' => 'In Lesezeichen',
    'liked' => 'Angemeldet',
  ),
  'categories' =>
  array (
    'love' => 'Liebe',
    'nature' => 'Natur',
    'life' => 'Leben',
    'death' => 'Tod',
    'war' => 'Krieg',
    'peace' => 'Frieden',
    'family' => 'Familie',
    'friendship' => 'Freundschaft',
    'travel' => 'Reise',
    'work' => 'Arbeit',
    'politics' => 'Politik',
    'religion' => 'Religion',
    'philosophy' => 'Philosophie',
    'humor' => 'Umorismus',
    'sadness' => 'Trauer',
    'joy' => 'Freude',
    'hope' => 'Hoffnung',
    'despair' => 'Dispersion',
    'freedom' => 'Freiheit',
    'justice' => 'Gerichtshof',
    'other' => 'Sonstige',
  ),
  'poem_types' =>
  array (
    'sonnet' => 'Samen',
    'haiku' => 'Haiku',
    'limerick' => 'Limerick',
    'free_verse' => 'Frei',
    'rhymed' => 'Im Reim',
    'blank_verse' => 'Zurück zur Übersicht',
    'epic' => 'Episode',
    'lyric' => '- Ja',
    'narrative' => 'Narben',
    'dramatic' => 'Drama',
    'elegy' => 'Wahl',
    'ode' => 'O',
    'ballad' => 'Tanz',
    'villanelle' => 'Villanella',
    'sestina' => 'Land',
    'other' => 'Sonstige',
  ),
  'languages' =>
  array (
    'italian' => 'Italienisch',
    'english' => 'Englisch',
    'french' => 'Französisch',
    'spanish' => 'Spanisch',
    'german' => 'Deutsch',
    'portuguese' => 'Portugiesisch',
    'russian' => 'Russisch',
    'chinese' => 'China',
    'japanese' => 'Japan',
    'arabic' => 'Arabisch',
    'latin' => 'Laien',
    'greek' => 'Griechisch',
    'other' => 'Sonstige',
  ),
  'share_title' => 'Teilen Sie dieses Gedicht',
  'share_text' => 'Sehen Sie dieses schöne Gedicht auf Slamin',
  'url_copied' => 'URL in die Zwischenablage kopiert!',
  'delete_confirm' => 'Sind Sie sicher, dass Sie dieses Gedicht löschen möchten? Diese Aktion kann nicht aufgehoben werden.',
  'login_to_interact' => 'Zugang zur Interaktion mit Gedichten',
  'translation_confirm' => 'Bist du sicher, dass du eine Übersetzung dieses Gedichts anfordern willst?',
  'translation_requested' => 'Antrag auf Übersetzung erfolgreich gesendet!',
  'translation_error' => 'Fehler beim Senden der Übersetzungsanfrage',
  'stats' =>
  array (
    'views' => 'Ansichten',
    'likes' => 'Mir gefällt es',
    'comments' => 'Bemerkungen',
    'bookmarks' => 'Lesezeichen',
  ),
  'placeholders' =>
  array (
    'search' => 'Suche nach Titel, Inhalt, Autor..',
  ),
  'no_poems_found' => 'Keine Gedichte gefunden',
  'no_poems_description' => 'Es gibt keine Gedichte, die Ihren Suchkriterien entsprechen.',
  'tooltips' =>
  array (
    'comment_placeholder' => 'Schreibe deinen Kommentar. .',
    'post_comment' => 'Öffentlicher Kommentar',
  ),
  'tags' => 'Tag',
  'about_author' => 'Über den Autor',
  'no_bio' => 'Keine Bio verfügbar',
  'total_likes' => 'Ich mag total',
  'member_since' => 'Mitglied',
  'related_poems' => 'Verwandte Gedichte',
  'statistics' => 'Statistik',
  'words' => 'Wörter',
  'shares' => 'Teilen',
  'translation_requests' => 'Übersetzung',
  'comments' => 'Bemerkungen',
  'no_comments' => 'Noch keine Kommentare',
);
