<?php

return array (
  'search' => 'Suchen',
  'search_placeholder' => '[de] Cerca poesie, eventi, video...',
  'search_results' => '[de] Risultati di Ricerca',
  'results_for' => '[de] Risultati per',
  'results_found' => '[de] risultati trovati',
  'no_results' => '[de] Nessun risultato trovato',
  'no_results_found' => '[de] Nessun risultato trovato',
  'start_typing' => '[de] Inizia a digitare per cercare...',
  'start_searching' => '[de] Inizia a Cercare',
  'search_description' => '[de] Cerca tra poesie, eventi, video, gig e utenti della community',
  'loading' => '[de] Caricamento...',
  'view_all' => '[de] Vedi Tutti',
  'new_search' => '[de] Nuova Ricerca',
  'try_different_keywords' => '[de] Prova con parole chiave diverse',
  'all' => 'Alle',
  'poems' => '[de] Poesie',
  'events' => '[de] Eventi',
  'videos' => '[de] Video',
  'gigs' => '[de] Gig',
  'users' => '[de] Utenti',
  'search_type_all' => '[de] Tutti i contenuti',
  'search_type_poems' => '[de] Solo poesie',
  'search_type_events' => '[de] Solo eventi',
  'search_type_videos' => '[de] Solo video',
  'search_type_gigs' => '[de] Solo gig',
  'search_type_users' => '[de] Solo utenti',
  'results_count' => '[de] {count} risultati',
  'no_results_for_query' => '[de] Nessun risultato per "{query}"',
  'search_suggestions' => '[de] Suggerimenti di ricerca',
  'refine_search' => '[de] Affina la ricerca',
  'clear_search' => '[de] Cancella ricerca',
  'search_error' => '[de] Errore durante la ricerca',
  'search_too_short' => '[de] Inserisci almeno 2 caratteri per la ricerca',
  'search_timeout' => '[de] Timeout della ricerca, riprova',
  'search_input_label' => '[de] Campo di ricerca globale',
  'search_results_label' => '[de] Risultati di ricerca',
  'search_category_label' => '[de] Categoria: {category}',
  'search_result_label' => '[de] Risultato: {title}',
);
