<?php

return array (
  'management' => 'Gestion du carrousel',
  'breadcrumb' => 'Carrousel',
  'dashboard' => 'Tableau de bord',
  'new_slide' => 'Nouveau',
  'edit' => 'Modifier',
  'view' => 'Affichage',
  'delete' => 'Supprimer',
  'cancel' => 'Annuler',
  'active' => 'Actif',
  'inactive' => 'Inactif',
  'image_header' => 'Image',
  'title_header' => 'Titre',
  'status_header' => 'État',
  'dates_header' => 'Dates',
  'actions_header' => 'Actions',
  'no_slides' => 'Aucune diapositive de carrousel trouvée',
  'delete_confirmation_title' => 'Confirmation Élimination',
  'delete_confirmation_message' => 'Voulez-vous vraiment supprimer cette diapositive de carrousel ?',
  'delete_confirmation_warning' => 'Cette action ne peut être annulée.',
  'slides_description' => 'Gérer les diapositives carrousel page d\'accueil',
  'create_first_slide' => 'Créez votre première page d\'accueil carrousel slide',
  'create_first_slide_button' => 'Créer la première diapositive',
  'slides' => 'Slide del Carosello',
  'from' => 'De',
  'to' => 'A',
);
