<?php

return array (
  'title' => '[fr] Ingaggi',
  'gigs' => '[fr] Ingaggi',
  'my_gigs' => '[fr] I Miei Ingaggi',
  'all_gigs' => '[fr] Tutti gli Ingaggi',
  'open_gigs' => '[fr] Ingaggi Aperti',
  'closed_gigs' => '[fr] Ingaggi Chiusi',
  'translation_jobs' => '[fr] Lavori di Traduzione',
  'translation_jobs_description' => '[fr] Traduci poesie e guadagna',
  'create_gig' => '[fr] Crea Ingaggio',
  'edit_gig' => '[fr] Modifica Ingaggio',
  'manage_gigs' => '[fr] Gestisci Ingaggi',
  'apply_gig' => '[fr] Candidati',
  'close_gig' => '[fr] Chiudi Ingaggio',
  'reopen_gig' => '[fr] Riapri Ingaggio',
  'delete_gig' => '[fr] Elimina Ingaggio',
  'fields' => 
  array (
    'title' => '[fr] Titolo Posizione',
    'description' => '[fr] Descrizione',
    'requirements' => '[fr] Requisiti',
    'compensation' => '[fr] Compenso',
    'deadline' => '[fr] Scadenza Candidature',
    'event' => '[fr] Evento',
    'group' => '[fr] Gruppo',
    'category' => '[fr] Categoria',
    'type' => '[fr] Tipo di Ingaggio',
    'language' => '[fr] Lingua',
    'location' => '[fr] Località',
    'is_remote' => '[fr] Lavoro Remoto',
    'is_urgent' => '[fr] Urgente',
    'is_featured' => '[fr] In Evidenza',
    'max_applications' => '[fr] Numero Massimo Candidature',
    'allow_group_admin_edit' => '[fr] Permetti Modifica Admin Gruppo',
  ),
  'types' => 
  array (
    'artist_poet' => '[fr] Artista/Poeta',
    'mc_guest' => '[fr] MC/Ospite',
    'technical_support' => '[fr] Supporto Tecnico',
    'volunteer' => '[fr] Volontaria/Volontario',
  ),
  'categories' => 
  array (
    'traduzione' => '[fr] Traduzione',
    'poetry_slam' => '[fr] Poetry Slam',
    'theater' => '[fr] Teatro',
    'music' => '[fr] Musica',
    'dance' => '[fr] Danza',
    'comedy' => '[fr] Commedia',
    'workshop' => '[fr] Workshop',
    'festival' => '[fr] Festival',
    'conference' => '[fr] Conferenza',
    'exhibition' => '[fr] Mostra',
    'competition' => '[fr] Competizione',
    'other' => '[fr] Altro',
  ),
  'status' => 
  array (
    'title' => '[fr] Stato',
    'open' => '[fr] Aperto',
    'closed' => '[fr] Chiuso',
    'urgent' => '[fr] Urgente',
    'featured' => '[fr] In Evidenza',
    'expired' => '[fr] Scaduto',
    'filled' => '[fr] Coperto',
    'cancelled' => '[fr] Annullato',
  ),
  'filters' => 
  array (
    'title' => '[fr] Filtri e Ricerca',
    'search' => '[fr] Cerca ingaggi...',
    'filter_by_category' => '[fr] Filtra per categoria',
    'filter_by_type' => '[fr] Filtra per tipo',
    'filter_by_location' => '[fr] Filtra per località',
    'filter_by_status' => '[fr] Filtra per stato',
    'sort_by' => '[fr] Ordina per',
    'sort_options' => 
    array (
      'recent' => '[fr] Più recenti',
      'deadline' => '[fr] Scadenza',
      'urgent' => '[fr] Urgenti',
      'featured' => '[fr] In evidenza',
      'compensation' => '[fr] Compenso',
      'applications' => '[fr] Numero candidature',
    ),
    'select_category' => '[fr] Seleziona categoria',
    'select_type' => '[fr] Seleziona tipo',
    'select_language' => '[fr] Seleziona lingua',
    'select_event' => '[fr] Seleziona evento',
    'select_group' => '[fr] Seleziona gruppo',
    'show_remote' => '[fr] Solo remoto',
    'show_urgent' => '[fr] Solo urgenti',
    'show_featured' => '[fr] Solo in evidenza',
  ),
  'management' => 
  array (
    'title' => '[fr] Gestione Ingaggi',
    'manage_applications' => '[fr] Gestisci Candidature',
    'view_applications' => '[fr] Visualizza Candidature',
    'send_global_message' => '[fr] Invia Messaggio Globale',
    'global_message_placeholder' => '[fr] Scrivi un messaggio per tutti i professionisti...',
    'send_message' => '[fr] Invia Messaggio',
    'message_sent' => '[fr] Messaggio inviato con successo!',
    'extend_deadline' => '[fr] Estendi Scadenza',
    'new_deadline' => '[fr] Nuova Scadenza',
    'deadline_extended' => '[fr] Scadenza estesa con successo!',
    'close_applications' => '[fr] Chiudi Candidature',
    'reopen_applications' => '[fr] Riapri Candidature',
    'close_confirm' => '[fr] Sei sicuro di voler chiudere le candidature?',
    'reopen_confirm' => '[fr] Sei sicuro di voler riaprire le candidature?',
    'delete_confirm' => '[fr] Sei sicuro di voler eliminare questo ingaggio?',
    'allow_group_admin_edit_help' => '[fr] Permetti agli admin del gruppo di modificare questo ingaggio',
  ),
  'actions' => 
  array (
    'read' => '[fr] Leggi',
    'share' => '[fr] Condividi',
    'close_gig' => '[fr] Chiudi Ingaggio',
    'reopen_gig' => '[fr] Riapri Ingaggio',
    'send_global_message' => '[fr] Invia Messaggio Globale',
    'view_gig' => '[fr] Vedi Ingaggio',
    'message' => 'Message',
    'message_placeholder' => '[fr] Scrivi il tuo messaggio per tutti gli utenti...',
    'send_message' => '[fr] Invia Messaggio',
    'confirm_close' => '[fr] Conferma Chiusura',
    'confirm_close_text' => '[fr] Sei sicuro di voler chiudere questo ingaggio? Non sarà più possibile ricevere nuove candidature.',
    'confirm_reopen' => '[fr] Conferma Riapertura',
    'confirm_reopen_text' => '[fr] Sei sicuro di voler riaprire questo ingaggio? Potrà ricevere nuove candidature.',
  ),
  'remote' => '[fr] Remoto',
  'applications' => 
  array (
    'title' => '[fr] Candidature',
    'my_applications' => '[fr] Le Mie Candidature',
    'pending_applications' => '[fr] Candidature in Attesa',
    'accepted_applications' => '[fr] Candidature Accettate',
    'rejected_applications' => '[fr] Candidature Rifiutate',
    'manage_applications' => '[fr] Gestisci Candidature',
    'applications_list' => '[fr] Lista Candidature',
    'total_applications' => '[fr] Candidature Totali',
    'max_positions' => '[fr] Posizioni Massime',
    'pending' => '[fr] In Attesa',
    'accepted' => '[fr] Accettata',
    'rejected' => '[fr] Rifiutata',
    'withdrawn' => '[fr] Ritirata',
    'experience' => '[fr] Esperienza',
    'portfolio' => '[fr] Portfolio',
    'view_portfolio' => '[fr] Vedi Portfolio',
    'compensation_expectation' => '[fr] Aspettative Compenso',
    'accept' => '[fr] Accetta',
    'reject' => '[fr] Rifiuta',
    'withdraw' => '[fr] Ritira Candidatura',
    'confirm_accept' => '[fr] Conferma Accettazione',
    'confirm_accept_text' => '[fr] Sei sicuro di voler accettare questa candidatura?',
    'confirm_reject' => '[fr] Conferma Rifiuto',
    'confirm_reject_text' => '[fr] Sei sicuro di voler rifiutare questa candidatura?',
    'withdraw_confirm' => '[fr] Sei sicuro di voler ritirare la tua candidatura?',
    'no_applications' => '[fr] Nessuna Candidatura',
    'no_applications_description' => '[fr] Non ci sono ancora candidature per questo ingaggio.',
    'apply' => '[fr] Candidati',
    'message' => '[fr] Messaggio di Candidatura',
    'message_placeholder' => '[fr] Presentati e spiega perché sei interessato a questa posizione...',
    'experience_placeholder' => '[fr] Descrivi la tua esperienza rilevante...',
    'portfolio_placeholder' => '[fr] Link al tuo portfolio o sito web...',
    'availability_placeholder' => '[fr] Descrivi la tua disponibilità...',
    'compensation_expectation_placeholder' => '[fr] Le tue aspettative di compenso...',
    'submit_application' => '[fr] Invia Candidatura',
    'application_sent' => '[fr] Candidatura inviata con successo!',
    'application_withdrawn' => '[fr] Candidatura ritirata con successo!',
    'already_applied' => '[fr] Ti sei già candidato per questo ingaggio',
  ),
  'messages' => 
  array (
    'application_accepted' => '[fr] Candidatura accettata con successo!',
    'application_rejected' => '[fr] Candidatura rifiutata con successo!',
    'gig_closed' => '[fr] Ingaggio chiuso con successo!',
    'gig_reopened' => '[fr] Ingaggio riaperto con successo!',
    'gig_shared' => '[fr] Ingaggio condiviso con :count utenti!',
    'global_message_sent' => '[fr] Messaggio globale inviato a :count utenti!',
    'audience_not_allowed' => '[fr] Gli utenti audience non possono accedere agli ingaggi',
  ),
  'stats' => 
  array (
    'total_gigs' => '[fr] Ingaggi Totali',
    'open_gigs_count' => '[fr] Ingaggi Aperti',
    'urgent_gigs_count' => '[fr] Ingaggi Urgenti',
    'total_applications' => '[fr] Candidature Totali',
    'applications' => '[fr] Candidature',
    'pending_applications_count' => '[fr] Candidature in Attesa',
    'accepted_applications_count' => '[fr] Candidature Accettate',
    'my_applications_count' => '[fr] Le Mie Candidature',
    'my_gigs_count' => '[fr] I Miei Ingaggi',
    'browse_all' => '[fr] Sfoglia Tutti',
  ),
  'placeholders' => 
  array (
    'title' => '[fr] Es: Performer Poetry Slam per Evento Estivo',
    'description' => '[fr] Descrivi dettagliatamente la posizione, le responsabilità e le aspettative...',
    'requirements' => '[fr] Specifica i requisiti, competenze e esperienze richieste...',
    'compensation' => '[fr] Specifica il compenso offerto (es: €200, gratuito, percentuale...)',
    'location' => '[fr] Città, regione o "Remoto"',
    'deadline' => '[fr] Seleziona data e ora di scadenza',
    'max_applications' => '[fr] Numero massimo di candidature accettate',
  ),
  'help' => 
  array (
    'title' => '[fr] Sii specifico e accattivante nel titolo',
    'description' => '[fr] Fornisci tutti i dettagli necessari per attirare i candidati giusti',
    'requirements' => '[fr] Sii chiaro sui requisiti per evitare candidature inappropriate',
    'compensation' => '[fr] Specifica chiaramente il compenso per attirare candidati qualificati',
    'deadline' => '[fr] Imposta una scadenza ragionevole per ricevere candidature di qualità',
    'max_applications' => '[fr] Imposta un limite ragionevole per gestire le candidature',
    'is_remote' => '[fr] Seleziona se il lavoro può essere svolto da remoto',
    'is_urgent' => '[fr] Marca come urgente per attirare più attenzione',
    'is_featured' => '[fr] Metti in evidenza per dare più visibilità',
    'event' => '[fr] Associa l\'ingaggio a un evento specifico',
    'group' => '[fr] Associa l\'ingaggio a un gruppo specifico',
    'allow_group_admin_edit' => '[fr] Se attivato, gli admin del gruppo potranno modificare questo ingaggio',
  ),
  'languages' => 
  array (
    'italian' => '[fr] Italiano',
    'english' => '[fr] Inglese',
    'french' => '[fr] Francese',
    'german' => '[fr] Tedesco',
    'spanish' => '[fr] Spagnolo',
    'portuguese' => '[fr] Portoghese',
    'russian' => '[fr] Russo',
    'chinese' => '[fr] Cinese',
    'japanese' => '[fr] Giapponese',
    'arabic' => '[fr] Arabo',
    'other' => '[fr] Altro',
  ),
  'breadcrumb' => 
  array (
    'gigs' => '[fr] Ingaggi',
    'my_gigs' => '[fr] I Miei Ingaggi',
    'create_gig' => '[fr] Crea Ingaggio',
    'edit_gig' => '[fr] Modifica Ingaggio',
    'manage_gigs' => '[fr] Gestisci Ingaggi',
    'applications' => '[fr] Candidature',
  ),
  'create' => 
  array (
    'publication_options' => '[fr] Opzioni di Pubblicazione',
  ),
  'about_author' => '[fr] Informazioni Autore',
  'organizer_section' => 
  array (
    'title' => '[fr] I Miei Eventi',
    'gigs' => '[fr] Ingaggi',
    'add_gig' => '[fr] Aggiungi Ingaggio',
    'no_events' => '[fr] Non hai ancora eventi',
    'create_event_first' => '[fr] Crea prima un evento per aggiungere ingaggi',
  ),
  'notifications' => 
  array (
    'shared_title' => '[fr] Nuovo Ingaggio Condiviso',
    'shared_message' => '[fr] :title per l\'evento :event - Posizione: :type - Luogo: :location - Scadenza: :deadline',
  ),
);
