<?php

return array (
  'carousel' => 
  array (
    'previous' => 'Précédent',
    'next' => '[fr] Successivo',
  ),
  'stats' => 
  array (
    'total_videos' => '[fr] Video Totali',
    'total_views' => '[fr] Visualizzazioni',
    'total_events' => '[fr] Eventi',
    'total_users' => '[fr] Utenti',
  ),
  'upcoming_events' => '[fr] Prossimi Eventi',
  'new_users' => '[fr] Nuovi Utenti',
  'poetry_section' => '[fr] Poesia',
  'articles_section' => '[fr] Articoli',
  'videos_section' => '[fr] Video',
  'no_videos_available' => '[fr] Nessun video disponibile',
  'no_videos_description' => '[fr] Al momento non ci sono video popolari da mostrare.',
  'upload_first_video' => '[fr] Carica il primo video',
  'login_to_upload' => '[fr] Accedi per caricare video',
  'details' => '[fr] Dettagli',
  'watch_video' => '[fr] Guarda Video',
  'create_poetry' => '[fr] Crea poesia',
  'view_all_poems' => '[fr] Vedi tutte le poesie',
  'upload_video' => '[fr] Carica video',
  'view_all_videos' => '[fr] Vedi tutti i video',
  'cancel' => 'Annuler',
  'video_author' => '[fr] Autore del video',
  'location_not_specified' => '[fr] Località non specificata',
  'follower' => '[fr] Follower',
  'following' => '[fr] Following',
  'editorial' => '[fr] Redazione',
  'interactions' => '[fr] Interazioni',
  'views' => '[fr] Visualizzazioni',
  'likes' => '[fr] Mi Piace',
  'most_popular' => '[fr] Più Popolare',
  'video_player' => '[fr] Video Player',
  'loading_video' => '[fr] Caricamento video...',
  'video_loading_error' => '[fr] Errore nel caricamento del video',
  'preview_not_available' => '[fr] Anteprima non disponibile',
  'create_snap' => '[fr] Crea snap',
  'snap_title_optional' => '[fr] Titolo (opzionale)',
  'snap_description_optional' => '[fr] Descrizione (opzionale)',
  'timestamp' => '[fr] Timestamp:',
  'create_snap_button' => '[fr] Crea Snap',
  'new_videos' => '[fr] Video Recenti',
);
