<?php

return array (
  'permissions' => '[fr] Permessi',
  'roles' => '[fr] Ruoli',
  'users' => '[fr] Utenti',
  'total_roles' => '[fr] Ruoli Totali',
  'total_permissions' => '[fr] Total Permissions',
  'total_users' => '[fr] Total Users',
  'roles_with_permissions' => '[fr] Ruoli Attivi',
  'role_management' => '[fr] 👥 Gestione',
  'role_security' => '[fr] 🔐 Sicurezza',
  'role_users' => '[fr] 👤 Utenti',
  'role_statistics' => '[fr] 📊 Statistiche',
  'manage_users' => '[fr] Gestisci Utenti',
  'users_description' => '[fr] Gestisci tutti gli utenti del sistema e assegna ruoli e permessi',
  'export' => '[fr] Esporta',
  'bulk_assign' => '[fr] Assegnazione di Massa',
  'search_users' => '[fr] Cerca Utenti',
  'search_placeholder' => '[fr] Cerca per nome, email o nickname...',
  'filter_by_role' => '[fr] Filtra per Ruolo',
  'all_roles' => '[fr] Tutti i Ruoli',
  'filter_by_status' => '[fr] Filtra per Stato',
  'all_status' => '[fr] Tutti gli Stati',
  'status_active' => 'Actif',
  'status_inactive' => 'Inactif',
  'items_per_page' => '[fr] Elementi per Pagina',
  'system_users' => '[fr] Utenti del Sistema',
  'name' => '[fr] Nome:',
  'email' => 'Email',
  'nickname' => '[fr] Nickname:',
  'status' => '[fr] Stato',
  'actions' => '[fr] Azioni',
  'no_nickname' => '[fr] Nessun nickname',
  'no_roles' => '[fr] No roles',
  'no_direct_permissions' => '[fr] Nessun permesso diretto',
  'view_details' => '[fr] Visualizza Dettagli',
  'edit_roles' => '[fr] Modifica Ruoli',
  'edit_permissions' => '[fr] Modifica Permessi',
  'delete_user' => '[fr] Elimina Utente',
  'view' => 'Voir',
  'manage_roles' => '[fr] Gestisci Ruoli',
  'manage_permissions' => '[fr] Gestisci Permessi',
);
