<?php

return array (
  'search' => 'Rechercher',
  'search_placeholder' => '[fr] Cerca poesie, eventi, video...',
  'search_results' => '[fr] Risultati di Ricerca',
  'results_for' => '[fr] Risultati per',
  'results_found' => '[fr] risultati trovati',
  'no_results' => '[fr] Nessun risultato trovato',
  'no_results_found' => '[fr] Nessun risultato trovato',
  'start_typing' => '[fr] Inizia a digitare per cercare...',
  'start_searching' => '[fr] Inizia a Cercare',
  'search_description' => '[fr] Cerca tra poesie, eventi, video, gig e utenti della community',
  'loading' => '[fr] Caricamento...',
  'view_all' => '[fr] Vedi Tutti',
  'new_search' => '[fr] Nuova Ricerca',
  'try_different_keywords' => '[fr] Prova con parole chiave diverse',
  'all' => 'Tous',
  'poems' => '[fr] Poesie',
  'events' => '[fr] Eventi',
  'videos' => '[fr] Video',
  'gigs' => '[fr] Gig',
  'users' => '[fr] Utenti',
  'search_type_all' => '[fr] Tutti i contenuti',
  'search_type_poems' => '[fr] Solo poesie',
  'search_type_events' => '[fr] Solo eventi',
  'search_type_videos' => '[fr] Solo video',
  'search_type_gigs' => '[fr] Solo gig',
  'search_type_users' => '[fr] Solo utenti',
  'results_count' => '[fr] {count} risultati',
  'no_results_for_query' => '[fr] Nessun risultato per "{query}"',
  'search_suggestions' => '[fr] Suggerimenti di ricerca',
  'refine_search' => '[fr] Affina la ricerca',
  'clear_search' => '[fr] Cancella ricerca',
  'search_error' => '[fr] Errore durante la ricerca',
  'search_too_short' => '[fr] Inserisci almeno 2 caratteri per la ricerca',
  'search_timeout' => '[fr] Timeout della ricerca, riprova',
  'search_input_label' => '[fr] Campo di ricerca globale',
  'search_results_label' => '[fr] Risultati di ricerca',
  'search_category_label' => '[fr] Categoria: {category}',
  'search_result_label' => '[fr] Risultato: {title}',
);
