<?php

return [
    'manage_event' => 'Gestisci evento',
    'requirements_participants' => 'Requisiti per partecipanti (opzionale)',
    'max_participants_optional' => 'Numero massimo partecipanti (opzionale)',
    'max_participants_help' => 'Numero massimo di partecipanti ammesse/i',
    'confirmed_participants' => 'Confermati',
    'pending_participants' => 'In attesa di conferma',
    'participant_stats' => 'Statistiche ruoli',
    'first_participant' => 'Diventa la/il prima/o partecipante!',
    'participant_invited' => 'Invitato',
    'participant_applied' => 'Applicato',
    'confirmed_participants_list' => 'Partecipanti confermate/i',
    'manage_event_action' => 'Gestisci evento',
    'invite_users' => 'Invita utenze',
    'invite_users_help' => 'Per eventi privati, invita utenze specifiche',
    'no_invited_users' => 'Nessun\'utenza invitata',
    'participant_apply_title' => 'Richiesta partecipazione',
    'participant_apply_role' => 'Ruolo richiesto',
    'participant_apply_role_help' => 'Seleziona il ruolo per cui ti candidi',
    'participant_apply_message' => 'Messaggio di presentazione',
    'participant_apply_message_help' => 'Presentati e spiega perché vuoi partecipare a questo evento. Racconta la tua passione per la poesia e cosa ti motiva...',
    'participant_apply_message_suggestion' => 'Suggerimento: menziona la tua esperienza, il tuo stile e perché questo evento ti interessa',
    'participant_apply_experience' => 'Esperienza poetica',
    'participant_apply_experience_help' => 'Descrivi la tua esperienza: eventi a cui hai partecipato, anni di attività, stile, riconoscimenti...',
    'participant_apply_experience_optional' => 'Opzionale ma consigliato per aumentare le tue possibilità',
    'participant_apply_send' => 'Invia candidatura',
    'participant_apply_cancel' => 'Annulla',
    'participant_apply_sending' => 'Invio in corso...',
    'participant_apply_validation_role' => 'Seleziona un ruolo',
    'participant_apply_validation_message' => 'Inserisci un messaggio di presentazione',
    'participant_apply_validation_terms' => 'Devi accettare i termini',
    'participant_links' => 'Link portfolio',
    'participant_links_help' => 'Video performance, social media, siti web, ecc.',
    'participant_links_placeholder' => 'https://youtube.com/watch?v=... o https://instagram.com/...',
    'participant_terms_accept' => 'Confermo di aver letto e accetto i termini dell\'evento. La mia candidatura sarà valutata dall\'organizzatore e riceverò una notifica con la risposta.',
    'organizer' => 'Organizzatrice/Organizzatore',
    'participants_status' => 'Partecipanti',
    'max_participants_placeholder' => 'Numero massimo...',
    'organizer_label' => 'Organizzatore:',
    'participants_label' => 'Partecipanti:',
    'delete_warning_participants' => 'Chiunque partecipi riceverà una notifica di cancellazione',
    'invited_badge' => '📨 Invito inviato',
    'user_already_invited' => 'Utenza già invitata',
    'role_organizer' => 'Organizzatrice/Organizzatore',
    'action_invite' => 'Invita',
    'tooltip_invite' => 'Invita',
    'success_invited' => 'Invito inviato con successo',
    'festival_events_management_later' => 'Potrai gestire gli eventi del festival dalla pagina di modifica dopo la creazione',
    'invites_and_gig' => 'Inviti e ingaggi',
    'invites' => 'Inviti',
];
