<?php

return [
    'create_account' => 'Crea il tuo account',
    'complete_profile' => 'Completa il tuo profilo in pochi passaggi',
    'join_slam_in' => 'Unisciti a Slam In',
    'full_name_placeholder' => 'Inserisci il tuo nome completo',
    'password_min_characters' => '(minimo 8 caratteri)',
    'confirm_password' => 'Conferma password',
    'preferred_language' => 'Lingua preferita',
    'language_tip' => 'Potrai sempre cambiare la lingua in seguito, nelle impostazioni del tuo profilo.',
    'changing_language' => 'Cambiando lingua',
    'home_for_poetry' => 'Una casa per la poesia',
    'and' => 'e',
    'choose_role' => 'Scegli il tuo ruolo',
    'choose_role_description' => 'Seleziona uno o più ruoli che ti rappresentano meglio nella community di Slam In.',
    'poet' => 'Poeta',
    'venue_owner' => 'Proprietaria/o di luogo',
    'audience' => 'Pubblico',
    'poets' => 'Poete/i',
    'community' => 'Community',
    'only_essential_data' => 'Solo i dati essenziali per iniziare',
    'artists' => 'Artiste/i',
    'organizers' => 'Organizzatrici/Organizzatori',
    'role_admin_name' => 'Amministratrice/Amministratore',
    'role_moderator_name' => 'Community manager',
    'role_poet_name' => 'Poeta/Artista',
    'role_organizer_name' => 'Event manager',
    'role_judge_name' => 'Giudice competizioni',
    'role_venue_owner_name' => 'Proprietaria/o luogo',
    'role_technician_name' => 'Supporto tecnico professionale',
    'role_audience_name' => 'Pubblico/Fan',
    'role_admin_description' => 'Controllo completo della piattaforma Slam In',
    'role_moderator_description' => 'Moderazione contenuti e gestione community',
    'role_poet_description' => 'Partecipazione eventi, pubblicazione contenuti artistici',
    'role_organizer_description' => 'Creazione e gestione eventi slam',
    'role_venue_owner_description' => 'Gestione locali e prenotazioni spazi',
    'role_audience_description' => 'Partecipazione come pubblico, votazioni e interazioni',
    'role_special_description' => 'Ruolo speciale per la community',


    'already_have_account' => 'Hai già un account?',
    'complete_ecosystem' => 'Ecosistema completo',
    'email' => 'Email',
    'email_placeholder' => 'La tua email',
    'events_general' => 'Eventi',
    'fast_registration' => 'Registrazione veloce',
    'flexible_roles' => 'Ruoli flessibili',
    'four_main_roles' => 'Quattro ruoli principali',
    'full_name' => 'Nome completo',
    'login' => 'Accedi',
    'nickname' => 'Nickname',
    'nickname_placeholder' => 'Il tuo nickname pubblico',
    'optional' => 'Opzionale',
    'password' => 'Password',
    'register' => 'Registrati',
    'venues' => 'Venue',
    'why_join_slam_in' => 'Perché unirsi a Slam In?',


    'platform_description' => 'Platform description',
    'role_judge_description' => 'Role judge description',
    'role_technician_description' => 'Role technician description',

];