<?php

return array (
  'permissions' => '[en] Permessi',
  'roles' => '[en] Ruoli',
  'users' => '[en] Utenti',
  'total_roles' => '[en] Ruoli Totali',
  'total_permissions' => '[en] Total Permissions',
  'total_users' => '[en] Total Users',
  'roles_with_permissions' => '[en] Ruoli Attivi',
  'role_management' => '[en] 👥 Gestione',
  'role_security' => '[en] 🔐 Sicurezza',
  'role_users' => '[en] 👤 Utenti',
  'role_statistics' => '[en] 📊 Statistiche',
  'manage_users' => '[en] Gestisci Utenti',
  'users_description' => '[en] Gestisci tutti gli utenti del sistema e assegna ruoli e permessi',
  'export' => '[en] Esporta',
  'bulk_assign' => '[en] Assegnazione di Massa',
  'search_users' => '[en] Cerca Utenti',
  'search_placeholder' => '[en] Cerca per nome, email o nickname...',
  'filter_by_role' => '[en] Filtra per Ruolo',
  'all_roles' => '[en] Tutti i Ruoli',
  'filter_by_status' => '[en] Filtra per Stato',
  'all_status' => '[en] Tutti gli Stati',
  'status_active' => 'Active',
  'status_inactive' => 'Inactive',
  'items_per_page' => '[en] Elementi per Pagina',
  'system_users' => '[en] Utenti del Sistema',
  'name' => '[en] Nome:',
  'email' => 'Email',
  'nickname' => '[en] Nickname:',
  'status' => '[en] Stato',
  'actions' => '[en] Azioni',
  'no_nickname' => '[en] Nessun nickname',
  'no_roles' => '[en] No roles',
  'no_direct_permissions' => '[en] Nessun permesso diretto',
  'view_details' => '[en] Visualizza Dettagli',
  'edit_roles' => '[en] Modifica Ruoli',
  'edit_permissions' => '[en] Modifica Permessi',
  'delete_user' => '[en] Elimina Utente',
  'view' => 'View',
  'manage_roles' => '[en] Gestisci Ruoli',
  'manage_permissions' => '[en] Gestisci Permessi',
);
